{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 231,
   "id": "880e57ff-2e56-4334-a321-3e63e6fd992e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[(4, 3), (7, 2)]\n",
      "((5, 4, 8, 7, 6, 13, 12, 16, 17, 15, 14), (3, 2, 1, 0, 10, 11, 9))\n",
      "18\n",
      "\n",
      "N      3.357755    1.083744    0.210762\n",
      "C      2.240903    0.871546    0.443133\n",
      "C      0.825330    0.601905    0.732148\n",
      "C      0.538207   -0.926196    0.866165\n",
      "C     -2.493176   -1.013356   -2.485653\n",
      "C     -3.742756   -0.257428   -2.095661\n",
      "C     -3.481821    1.050361   -2.245845\n",
      "C     -2.047706    1.164813   -2.719085\n",
      "C     -1.997522   -0.090890   -3.601300\n",
      "H      0.538807    1.127266    1.651773\n",
      "H      1.431828   -1.531720    0.673319\n",
      "H      0.165436   -1.174683    1.866521\n",
      "H     -2.654391   -2.052366   -2.774099\n",
      "H     -4.660097   -0.696827   -1.732384\n",
      "H     -4.145464    1.872994   -2.024168\n",
      "H     -1.808445    2.097007   -3.233840\n",
      "H     -2.675429   -0.044589   -4.463483\n",
      "H     -0.991716   -0.341142   -3.956044\n",
      "\n",
      "18\n",
      "\n",
      "C     -4.167689    0.335263   -0.505140\n",
      "C     -4.112688   -0.779962    0.236700\n",
      "C     -3.787914   -0.427572    1.658775\n",
      "C     -3.671615    1.066727    1.584601\n",
      "C     -3.895064    1.476685    0.327984\n",
      "H     -4.381031    0.391040   -1.561779\n",
      "H     -4.275573   -1.784240   -0.123624\n",
      "H     -4.592383   -0.729439    2.335594\n",
      "H     -2.845125   -0.883340    1.974691\n",
      "H     -3.442028    1.705650    2.423651\n",
      "H     -3.878115    2.496632   -0.024906\n",
      "C      1.218743   -0.924713   -0.544114\n",
      "C      1.491347    0.129398    0.235024\n",
      "C      2.102713    1.310959   -0.265656\n",
      "N      2.601311    2.276840   -0.669685\n",
      "H      1.453034   -0.929263   -1.605472\n",
      "H      0.750973   -1.813196   -0.131461\n",
      "H      1.247212    0.108032    1.291342\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from rdkit import Chem\n",
    "from rdkit.Geometry import Point3D\n",
    "from rdkit.Chem import AllChem, rdMolAlign, rdchem\n",
    "import numpy as np\n",
    "\n",
    "def smiles_to_molecules(product, reactant_a, reactant_b): # takes 3 SMILES strings, outputs 3 molecules\n",
    "    product_mol = Chem.rdmolops.AddHs(Chem.rdmolfiles.MolFromSmiles(product))\n",
    "    reactant_a_mol = Chem.rdmolops.AddHs(Chem.rdmolfiles.MolFromSmiles(reactant_a))\n",
    "    reactant_b_mol = Chem.rdmolops.AddHs(Chem.rdmolfiles.MolFromSmiles(reactant_b))\n",
    "\n",
    "    return product_mol, reactant_a_mol, reactant_b_mol\n",
    "\n",
    "def diels_alder_identifier(product_mol, reactant_a_mol, reactant_b_mol): # takes 3 SMILES molecules, outputs a list of tuples\n",
    "    matched_a_final, _ = diels_alder_index(product_mol, reactant_a_mol, reactant_b_mol)\n",
    "    bond_candidates = []\n",
    "    \n",
    "    for atom_idx in matched_a_final:\n",
    "        atom_obj = product_mol.GetAtomWithIdx(atom_idx)\n",
    "        for neighbor_obj in atom_obj.GetNeighbors():\n",
    "            neighbor_idx = neighbor_obj.GetIdx()\n",
    "            if neighbor_idx not in matched_a_final:\n",
    "                bond_candidates.append((atom_idx, neighbor_idx))\n",
    "                \n",
    "    return bond_candidates\n",
    "    \n",
    "\n",
    "def diels_alder_index(product_mol, reactant_a_mol, reactant_b_mol): # takes 3 molecules, outputs two tuples\n",
    "    params = Chem.AdjustQueryParameters()\n",
    "    params.makeBondsGeneric = True\n",
    "    params.adjustDegree = False\n",
    "    params.adjustRingCount = False\n",
    "\n",
    "    query_a = Chem.AdjustQueryProperties(reactant_a_mol, params)\n",
    "    query_b = Chem.AdjustQueryProperties(reactant_b_mol, params)\n",
    "\n",
    "    matched_a_idx = product_mol.GetSubstructMatches(query_a)\n",
    "    matched_b_idx = product_mol.GetSubstructMatches(query_b)\n",
    "\n",
    "    if len(matched_a_idx) == 0 or len(matched_b_idx) == 0:\n",
    "        print(\"did not find matching substructures\")\n",
    "        return null\n",
    "\n",
    "    matched_a_final = ()\n",
    "    matched_b_final = ()\n",
    "    \n",
    "    for match_a in matched_a_idx:\n",
    "        for match_b in matched_b_idx:\n",
    "            if set(match_a).isdisjoint(match_b):\n",
    "                matched_a_final += match_a\n",
    "                matched_b_final += match_b\n",
    "    \n",
    "    if type(matched_a_final[0]) is not int or type(matched_b_final[0]) is not int:\n",
    "        print(\"too many matching substructures\")\n",
    "        return null\n",
    "\n",
    "    return matched_a_final, matched_b_final\n",
    "\n",
    "    \n",
    "def diels_alder_reverse(product_mol, reactant_a_mol, reactant_b_mol, idx1, idx2, idx3, idx4, separation): # takes 3 SMILES strings and 5 integers, outputs a molecule\n",
    "    status = AllChem.EmbedMolecule(product_mol)\n",
    "\n",
    "    if status == -1:\n",
    "        print(\"embedmolecule could not generate 3D coordinates\")\n",
    "    else:\n",
    "        AllChem.MMFFOptimizeMolecule(product_mol)\n",
    "        product_conf = product_mol.GetConformer()\n",
    "\n",
    "    bond12_vector = np.array(product_conf.GetAtomPosition(idx1)) - np.array(product_conf.GetAtomPosition(idx2))\n",
    "    bond34_vector = np.array(product_conf.GetAtomPosition(idx3)) - np.array(product_conf.GetAtomPosition(idx4))\n",
    "    separation_vector = separation * ((bond12_vector + bond34_vector)/np.linalg.norm(bond12_vector + bond34_vector)) # calculates reaction coordinate\n",
    "\n",
    "    matched_a_final, _ = diels_alder_index(product_mol, reactant_a_mol, reactant_b_mol)\n",
    "\n",
    "    for idx in matched_a_final: # moves apart reactant atoms\n",
    "        p_orig = product_conf.GetAtomPosition(idx)\n",
    "        new_x = p_orig.x + separation_vector[0]\n",
    "        new_y = p_orig.y + separation_vector[1]\n",
    "        new_z = p_orig.z + separation_vector[2]\n",
    "        new_pos = Point3D(new_x, new_y, new_z)\n",
    "        \n",
    "        product_conf.SetAtomPosition(idx, new_pos)\n",
    "\n",
    "    rw_mol = Chem.RWMol(product_mol)\n",
    "    rw_mol.RemoveBond(idx1, idx2)\n",
    "    rw_mol.RemoveBond(idx3, idx4) # breaks formed bonds\n",
    "    product_mol = rw_mol.GetMol()\n",
    "    Chem.SanitizeMol(product_mol)\n",
    "    \n",
    "    return product_mol\n",
    "\n",
    "def diels_alder_align(product_mol_reversed, reactant_a_mol, reactant_b_mol): # takes 3 molecules, outputs one molecule\n",
    "    matched_a, matched_b = diels_alder_index(product_mol_reversed, reactant_a_mol, reactant_b_mol)\n",
    "\n",
    "    AllChem.EmbedMolecule(reactant_a_mol)\n",
    "    AllChem.EmbedMolecule(reactant_b_mol)\n",
    "    AllChem.MMFFOptimizeMolecule(reactant_a_mol)\n",
    "    AllChem.MMFFOptimizeMolecule(reactant_b_mol)\n",
    "\n",
    "    atom_map_a = []\n",
    "    atom_map_b = []\n",
    "\n",
    "    for i, atom_idx in enumerate(matched_a):\n",
    "        atom_map_a.append((i, atom_idx))\n",
    "\n",
    "    for i, atom_idx in enumerate(matched_b):\n",
    "        atom_map_b.append((i, atom_idx))\n",
    "    \n",
    "    rdMolAlign.AlignMol(reactant_a_mol, product_mol_reversed, atomMap=atom_map_a)\n",
    "    rdMolAlign.AlignMol(reactant_b_mol, product_mol_reversed, atomMap=atom_map_b)\n",
    "\n",
    "    final_complex = Chem.CombineMols(reactant_a_mol, reactant_b_mol)\n",
    "    return final_complex\n",
    "\n",
    "\n",
    "def xyz_block(mol): # takes a molecule, outputs an xyz block\n",
    "    return Chem.rdmolfiles.MolToXYZBlock(mol,-1,6) #converts molecule to xyz coordinates\n",
    "\n",
    "prod, a, b = smiles_to_molecules(\"N#CC1CC2C=CC1C2\", \"C1=CCC=C1\", \"C=CC#N\")\n",
    "\n",
    "print(diels_alder_identifier(prod, a, b))\n",
    "\n",
    "print(diels_alder_index(prod, a, b))\n",
    "\n",
    "print(xyz_block(diels_alder_reverse(prod, a, b, 4, 3, 7, 2, 3)))\n",
    "\n",
    "prod_rev = diels_alder_reverse(prod, a, b, 4, 3, 7, 2, 3)\n",
    "\n",
    "print(xyz_block(diels_alder_align(prod_rev, a, b)))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac12c700-449d-4fb8-a022-016a0aad262c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
